### ISSUE TITLE
'plot_training' is not defined

### ISSUE THREAD

**Issue by HIN0209** [GeorgeSeif/Transfer-Learning-Suite#1]
@GeorgeSeif 
This is an interesting project. I tried this with dog vs. cat dataset (kaggle) that was running fine. The only problem was the error in plotting.

-------------------------------

Epoch 00019: saving model to ./checkpoints/DenseNet201_model_weights.h5
Epoch 20/20
703/703 [==============================] - 149s 212ms/step - loss: 0.0014 - acc: 0.9996 - val_loss: 0.1408 - val_acc: 0.9764

Epoch 00020: saving model to ./checkpoints/DenseNet201_model_weights.h5
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    plot_training(history)
NameError: name 'plot_training' is not defined

**Comment by HIN0209** [comment]
Self-response.

Copied & pasted the definition from utils.py [def plot_training(history):] just worked.

**Comment by dclin1471** [comment]
just add utils. in front of  plot_training(history)  like   utils.plot_training(history) can solve this problem
